- name: create Directories
  file: 
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ create_directories }}"
  tags: 
    - dotfiles
    
- name: Laydown dotfile.templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ dotfiles }}"
  tags: 
    - dotfiles 