- name: install desired packages for RedHat
  dnf:
    name: "{{ rhel_package_list }}"
    state: latest
  tags: 
    - packages

- name: install slack with yum or apt
  action: "dnf name=https://downloads.slack-edge.com/linux_releases/slack-3.3.3-0.1.fc21.x86_64.rpm"
  tags:
    - packages
