- name: Add rhel repositories
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    enabled: yes
  with_items: "{{ rhel_repos }}"

- name: Add rpmfusion yum repository
  dnf:
    name: "{{ item }}"
    state: latest
  with_items: "{{ dnf_repos }}"
