- name: Add rhel repositories
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    enabled: yes
  with_items: "{{ rhel_repos }}"

- name: Add rpmfusion yum repository
  dnf:
    name: "{{ item }}"
    state: latest
  with_items: "{{ dnf_repos }}"

- name: Add chrome DNF repository
  yum_repository:
    name: google-chrome
    description: Google Chrome Browser
    baseurl: "http://dl.google.com/linux/chrome/rpm/stable/{{ ansible_architecture }}"
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub
    gpgcheck: yes
    enabled: yes
